name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Helm deps
        run: |
          helm dependency update charts/airbyte/ 

      - name: Add Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add airbyte-bootloader https://airbytehq.github.io/helm-charts/
          helm repo add temporal https://airbytehq.github.io/helm-charts/
          helm repo add webapp https://airbytehq.github.io/helm-charts/
          helm repo add server https://airbytehq.github.io/helm-charts/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"